version: 2
group_defaults:
    approve_by_comment:
        enabled: true
        approve_regex: '^:\+1:'
    reset_on_push:
        enabled: false
    github_reviews:
        enabled: true
    author_approval:
        ignored: true
groups:
    secretaries-tag:
        required: 1
        teams:
            - secretaries
        conditions:
            labels:
                - "Internal: Bylaw or Admin Change"
                - "New PSR"
    secretaries-files:
        required: 1
        teams:
            - secretaries
        conditions:
            files:
                exclude:
                    - "proposed/*"
    http:
        required: 1
        teams:
            - psr-15
            - psr-17
        conditions:
            labels:
                - "HTTP"
            files:
                - "proposed/http-factory/*"
                - "proposed/http-middleware/*"
    cs-extended:
        required: 1
        teams:
            - psr-12
        conditions:
            files:
                - "proposed/extended-coding-style-guide*"
    http-client:
        required: 1
        teams:
            - psr-18
        conditions:
            files:
                - "proposed/http-client/*"
    security:
        required: 1
        teams:
            - psr-9-10
        conditions:
            files:
                - "proposed/security-*"
    doc:
        required: 1
        teams:
            - psr-5
        conditions:
            files:
                - "proposed/phpdoc*"
    event:
        required: 1
        teams:
            - psr-14
        conditions:
            files:
                - "proposed/event-manager*"
